## np.sort
- Return a sorted copy of an array.

In [1]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([82, 30, 62, 92,  3, 24, 87, 87, 99, 21, 48, 22, 61, 20, 34])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[88, 21, 52, 83],
       [44, 72, 14, 14],
       [73, 87, 34, 33],
       [ 2, 64, 75, 62],
       [34,  8, 70, 47],
       [44, 21, 47, 41]])

In [3]:
#sort 
np.sort(a)

array([ 3, 20, 21, 22, 24, 30, 34, 48, 61, 62, 82, 87, 87, 92, 99])

In [4]:
#Descending Order
np.sort(a)[::-1]

array([99, 92, 87, 87, 82, 62, 61, 48, 34, 30, 24, 22, 21, 20,  3])

In [5]:
np.sort(b,axis=0)

array([[ 2,  8, 14, 14],
       [34, 21, 34, 33],
       [44, 21, 47, 41],
       [44, 64, 52, 47],
       [73, 72, 70, 62],
       [88, 87, 75, 83]])

## np.append
- The numpy.append() appends values along the mentioned axis at the end of the array

In [6]:
a


array([82, 30, 62, 92,  3, 24, 87, 87, 99, 21, 48, 22, 61, 20, 34])

In [7]:
np.append(a,200)

array([ 82,  30,  62,  92,   3,  24,  87,  87,  99,  21,  48,  22,  61,
        20,  34, 200])

In [8]:
b

array([[88, 21, 52, 83],
       [44, 72, 14, 14],
       [73, 87, 34, 33],
       [ 2, 64, 75, 62],
       [34,  8, 70, 47],
       [44, 21, 47, 41]])

In [9]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[88.        , 21.        , 52.        , 83.        ,  0.97522481],
       [44.        , 72.        , 14.        , 14.        ,  0.27838592],
       [73.        , 87.        , 34.        , 33.        ,  0.91735699],
       [ 2.        , 64.        , 75.        , 62.        ,  0.36018798],
       [34.        ,  8.        , 70.        , 47.        ,  0.81520215],
       [44.        , 21.        , 47.        , 41.        ,  0.92568978]])

## np.concatenate

- numpy.concatenate() function concatenate a sequence of arrays along an existing axis.



In [10]:
c= np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [11]:
np.concatenate((c,d),axis= 0) # 0 --> row-wise

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
np.concatenate((c,d),axis= 1) # 1 --> column-wise

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

## np.unique
- With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

In [13]:
a


array([82, 30, 62, 92,  3, 24, 87, 87, 99, 21, 48, 22, 61, 20, 34])

In [14]:
# Finding the unique value
np.unique(a)

array([ 3, 20, 21, 22, 24, 30, 34, 48, 61, 62, 82, 87, 92, 99])

## np.expand_dims
- With the help of np.expand_dims() method, we can get the expanded dimensions of an array

In [15]:
a

array([82, 30, 62, 92,  3, 24, 87, 87, 99, 21, 48, 22, 61, 20, 34])

In [16]:
# syntax of np.expand_dims 
print(np.expand_dims(a,axis=1))

print(np.expand_dims(a,axis=1).shape)

[[82]
 [30]
 [62]
 [92]
 [ 3]
 [24]
 [87]
 [87]
 [99]
 [21]
 [48]
 [22]
 [61]
 [20]
 [34]]
(15, 1)


In [17]:
# column-wise
print(np.expand_dims(a,axis=0))
print(np.expand_dims(a,axis=0).shape)


[[82 30 62 92  3 24 87 87 99 21 48 22 61 20 34]]
(1, 15)


## np.where
- The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.
- jkuno condition er jonno index ber kora jay np.where(a> or any condition)
- jkuno condition onujayi change kora jay np.where(condition,True hole eta boshbe ,false)

In [18]:
a

array([82, 30, 62, 92,  3, 24, 87, 87, 99, 21, 48, 22, 61, 20, 34])

In [19]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  2,  3,  6,  7,  8, 12], dtype=int64),)

In [20]:
# replace all values > 50 with 0

np.where(a>50,0,a)

array([ 0, 30,  0,  0,  3, 24,  0,  0,  0, 21, 48, 22,  0, 20, 34])

In [21]:
# replace all even numbers with 0 
np.where(a%2 == 0,0,a)

array([ 0,  0,  0,  0,  3,  0, 87, 87, 99, 21,  0,  0, 61,  0,  0])

## np.argmax
- The numpy.argmax() function returns indices of the max element of the array in a particular axis.

In [22]:
a

array([82, 30, 62, 92,  3, 24, 87, 87, 99, 21, 48, 22, 61, 20, 34])

In [23]:
np.argmax(a)

8

In [24]:
b

array([[88, 21, 52, 83],
       [44, 72, 14, 14],
       [73, 87, 34, 33],
       [ 2, 64, 75, 62],
       [34,  8, 70, 47],
       [44, 21, 47, 41]])

In [25]:
np.argmax(b,axis=0)

array([0, 2, 3, 0], dtype=int64)

## np.argmin

In [26]:
# argmin
np.argmin(b,axis=1)

array([1, 2, 3, 0, 1, 1], dtype=int64)

## np.cumsum
1. previous value jug hoy
2. suppose Cricketer er previous match er runlist = 50,20,65,45,85,50,0,5 .prottek match er por jodi ba agee jante chawa hoy tar total run koto tolhon jevabe amra prothom (50+20=70) then next match (70+65= total) evabe jug hoy

In [27]:
# np.cumsum 
a

array([82, 30, 62, 92,  3, 24, 87, 87, 99, 21, 48, 22, 61, 20, 34])

In [28]:
np.cumsum(a)

array([ 82, 112, 174, 266, 269, 293, 380, 467, 566, 587, 635, 657, 718,
       738, 772])

In [29]:
b

array([[88, 21, 52, 83],
       [44, 72, 14, 14],
       [73, 87, 34, 33],
       [ 2, 64, 75, 62],
       [34,  8, 70, 47],
       [44, 21, 47, 41]])

In [30]:
np.cumsum(b,axis=0)

array([[ 88,  21,  52,  83],
       [132,  93,  66,  97],
       [205, 180, 100, 130],
       [207, 244, 175, 192],
       [241, 252, 245, 239],
       [285, 273, 292, 280]])

In [31]:
## np.cumprod
np.cumprod(a)

array([         82,        2460,      152520,    14031840,    42095520,
        1010292480,  1996099840,  1861994240,  -346163968,  1320491264,
       -1040928768, -1425596416, -1062035456,   234127360,  -629604352])

In [32]:
np.cumprod(b,axis=0)

array([[        88,         21,         52,         83],
       [      3872,       1512,        728,       1162],
       [    282656,     131544,      24752,      38346],
       [    565312,    8418816,    1856400,    2377452],
       [  19220608,   67350528,  129948000,  111740244],
       [ 845706752, 1414361088, 1812588704,  286382708]])

## np.percentile
- numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.
- ki poriman luk/value current value er cheye piche (0 percentile -> lowest , 100 -> Highest , 50 -> median )
- 75%tile means ki poriman value/luk pichone 

In [33]:
a

array([82, 30, 62, 92,  3, 24, 87, 87, 99, 21, 48, 22, 61, 20, 34])

In [34]:
np.percentile(a,50)

48.0

In [35]:
np.max(a)

99

In [36]:
np.percentile(a,100)

99.0

## np.histogram
- Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.
- It basically check frequency in a given range

In [37]:
a

array([82, 30, 62, 92,  3, 24, 87, 87, 99, 21, 48, 22, 61, 20, 34])

In [38]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 0, 4, 2, 1, 0, 2, 0, 3, 2], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

## np.corrcoef
- Return Pearson product-moment correlation coefficients.

In [39]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

## np.isin
- With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

- Eksathe multipe item search korte use hoy .suppose i have 5 numbers then i have to check those number against any array .

In [40]:
a

array([82, 30, 62, 92,  3, 24, 87, 87, 99, 21, 48, 22, 61, 20, 34])

In [41]:
#np.isin 
items = np.array([10,20,30,40,50,60,70,80,90,100])
#np.isin(a,items)  # check is there any matches
a[np.isin(a,items)] # Matches items array

array([30, 20])

# np.flip 
- The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [42]:
a

array([82, 30, 62, 92,  3, 24, 87, 87, 99, 21, 48, 22, 61, 20, 34])

In [43]:
np.flip(a) # Order reverse kore dey. Jeta shurute oita sheshe hobe

array([34, 20, 61, 22, 48, 21, 99, 87, 87, 24,  3, 92, 62, 30, 82])

In [44]:
b

array([[88, 21, 52, 83],
       [44, 72, 14, 14],
       [73, 87, 34, 33],
       [ 2, 64, 75, 62],
       [34,  8, 70, 47],
       [44, 21, 47, 41]])

In [45]:
np.flip(b) # Row and column both order has been changed

array([[41, 47, 21, 44],
       [47, 70,  8, 34],
       [62, 75, 64,  2],
       [33, 34, 87, 73],
       [14, 14, 72, 44],
       [83, 52, 21, 88]])

In [46]:
np.flip(b,axis=0) # only row

array([[44, 21, 47, 41],
       [34,  8, 70, 47],
       [ 2, 64, 75, 62],
       [73, 87, 34, 33],
       [44, 72, 14, 14],
       [88, 21, 52, 83]])

## np.put
- jkuno array te any place ba index a value permanently change ba replace kore

In [47]:
a


array([82, 30, 62, 92,  3, 24, 87, 87, 99, 21, 48, 22, 61, 20, 34])

In [48]:
np.put(a,[2,5],[630,500])

In [49]:
a

array([ 82,  30, 630,  92,   3, 500,  87,  87,  99,  21,  48,  22,  61,
        20,  34])

## np.delete
- Can delete temporary
- jokhon run korle output ashbe tokhon temporary
- multiple item delete kora jay

In [50]:
a


array([ 82,  30, 630,  92,   3, 500,  87,  87,  99,  21,  48,  22,  61,
        20,  34])

In [51]:
np.delete(a,3)

array([ 82,  30, 630,   3, 500,  87,  87,  99,  21,  48,  22,  61,  20,
        34])

In [52]:
a


array([ 82,  30, 630,  92,   3, 500,  87,  87,  99,  21,  48,  22,  61,
        20,  34])

In [53]:
np.delete(a,[0,3,5])

array([ 30, 630,   3,  87,  87,  99,  21,  48,  22,  61,  20,  34])

## Set functions
- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [54]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [55]:
np.intersect1d(m,n)

array([3, 4, 5])

In [56]:
np.setdiff1d(n,m)

array([6, 7])

In [57]:
np.setxor1d(m,n) # common gula baade sobgula

array([1, 2, 6, 7])

In [58]:
m[np.in1d(m,1)] # given number ache ki na where 1 is a element

array([1])

## np.clip 
- ekta range a rakhe value-gula
- suppose ami chai amr value gula jeno 25 theke 75 er modde hoy .j gula 25 theke chuto oigula 25 dara replace hobe and Boro value 75 dara

In [59]:
a

array([ 82,  30, 630,  92,   3, 500,  87,  87,  99,  21,  48,  22,  61,
        20,  34])

In [60]:
np.clip(a,a_min=25,a_max=75)

array([75, 30, 75, 75, 25, 75, 75, 75, 75, 25, 48, 25, 61, 25, 34])

In [61]:
## 19. np.count_nonzero 
## 17. np.swapaxesa
# 18. np.uniform

: 