###  What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types arrays.

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

## Creating a Numpy Array

In [143]:
import numpy as np
numArr = np.array([14,15,85,856])
print(numArr)

[ 14  15  85 856]


###### Creating 2D Array

In [144]:
# Array MUst be HOMOGENOUS
numArr_02 = np.array([[56,69,54,35],[856,45,86,858]])
print(numArr_02)

[[ 56  69  54  35]
 [856  45  86 858]]


##### 3D Array

In [145]:
ar_o3 = np.array([[[5,6,85],[8,9,56],[8,56,58],[5,6,85]]])
print(ar_o3.ndim)  #Checking Dimension
print(ar_o3)

3
[[[ 5  6 85]
  [ 8  9 56]
  [ 8 56 58]
  [ 5  6 85]]]


In [146]:
#Creating Specific DataType Array

np.array([1,9,8,45,5],dtype = float)



array([ 1.,  9.,  8., 45.,  5.])

##### Arange use
- work as similar as range
- can be used almost similar way like the range 

In [147]:
# arange it works similer like range 

ar_04=np.arange(1,12)
print(ar_04)

#Another Like the gap values 
array_5 = np.arange(1,11,2)
print(array_5)

[ 1  2  3  4  5  6  7  8  9 10 11]
[1 3 5 7 9]


In [148]:
# Reshape 
# total items should be equal to the product of 2 items in reshape
#Example: Given 1 to 10 .we must choose using the product of the total elements either (2,5) or (5,2)
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

##### Using np.ones & np.zeros


In [149]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [150]:
#np.zeros
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [151]:
# np.random it will generate random numbers in between 0 to 1
np.random.random((4,4))

array([[0.01436073, 0.49463966, 0.28697779, 0.65935822],
       [0.39602069, 0.27076723, 0.96607536, 0.9323398 ],
       [0.85781066, 0.45004454, 0.76751377, 0.83310256],
       [0.66784705, 0.55142285, 0.89287728, 0.03030181]])

##### linspace
- it takes 3 parameter
- e.g np.linspace((-10,15,10))
- first parameter(-10) = lower limits,  
  second parameter(15) = upper limits,  
  Third parameter(10) = How many numbers you want

- It will generate number between similar distance.Any two numbers distance/difference will be equal


In [152]:
np.linspace(-10,15,10)

#custom_size = np.linspace(-10,15,10).reshape(5,2)
#print(custom_size)

array([-10.        ,  -7.22222222,  -4.44444444,  -1.66666667,
         1.11111111,   3.88888889,   6.66666667,   9.44444444,
        12.22222222,  15.        ])

##### creating Identity Matrix

In [153]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Array Attributes


## Important Notes About reshape(2,2,2)
#### The reshape function is used to change the shape of an array without changing its data. The reshape(2, 2, 2) command reshapes an array into a 3-dimensional array with dimensions 2x2x2 
- The first argument 2 specifies that the reshaped array will have 2 blocks.
- The second argument 2 specifies that each block will have 2 rows.
- The third argument 2 specifies that each row will have 2 columns.
### Caution

- The total number of elements in the original array must match the total number of elements in the reshaped array. For example, in this case, 2 * 2 * 2 = 8, which matches the 8 elements in the original array.
- If the dimensions do not match, NumPy will raise an error.

In [154]:
#ndim
a1 = np.arange(10)
a2 = np.arange(9).reshape(3,3)
a3 = np.arange(8,dtype=float).reshape(2,2,2)
a2.ndim


2

In [155]:
a3.itemsize

8

In [156]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
int32
float64


##### shape
- How many rows and columns
- also dimension

In [157]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

##### itemsize
- how many bits are taking

In [158]:
a1.itemsize

4

#### size
- total size of the array

In [159]:
print(a3)
print(np.size(a3))

[[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]
8


#### astype 
- jodi kokhono datatype change korte hoy
- e.g int64 to int32
- reduce size

In [160]:
# astype 

a3.astype(np.int64)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

# Array Operation

#### Scaler Operation
- matrix er moto 
-  5 x matrix means prottek element er sathe 5 gun

In [161]:
print(a2)
print("\n\n After Multiplication -> ")
print(a2*2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


 After Multiplication -> 
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


#### Relational Operation 
- Performing relational operation  like < , > , == ,<= etc

In [162]:
# Relational
print(a2)
print("\n\n After  -> ")
print(a2==8)
print("\n\n After : -> ")
print(a2 > 4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


 After  -> 
[[False False False]
 [False False False]
 [False False  True]]


 After : -> 
[[False False False]
 [False False  True]
 [ True  True  True]]


In [163]:
# Vector Operationa1
# a2 + a2
a2 * a2


array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

# Array Functions 

#### max/min/sum/prod
- calculate max/min/prod
- axix=0 ->  column; axis = 1 -> row
- syntax: np.prod(a2) or  np.max(a2,axis=0 )

In [164]:
print(a2)
print("\nAfter operation -> ")
print(np.max(a2)) # higest in whole matrix

print("\n After operation -> ")
print(np.max(a2, axis=1))


[[0 1 2]
 [3 4 5]
 [6 7 8]]

After operation -> 
8

 After operation -> 
[2 5 8]


In [165]:
# mean/median/std/var
np.mean(a3) # can perform all

3.5

In [166]:
# Trigonomatrica
np.sin(a3)

array([[[ 0.        ,  0.84147098],
        [ 0.90929743,  0.14112001]],

       [[-0.7568025 , -0.95892427],
        [-0.2794155 ,  0.6569866 ]]])

#### Dot Product
- 1st matrix er column songkha == second matrix er Row songkha
- e.g (5,4) * (4*6)

In [167]:
m1 = np.random.random((5,4))*100
m2 = np.random.random((4,6))*100
print(m1)
print("\n After operation -> \n")
print(np.dot(m1,m2))

[[98.4087154  94.34094111 14.81930129 24.14717425]
 [ 3.10152163 16.91720203 66.3080162  66.8854135 ]
 [18.07362258 49.69302971 82.20885842 30.69754494]
 [14.37382549 84.8450132  27.26359846 57.21012404]
 [26.25721422 50.5534575  59.49743146 67.30451613]]

 After operation -> 

[[11260.9536131  12813.41957343  8512.61604194  9852.33714942
  16570.30936641 10575.40295726]
 [ 8496.93382351  2982.69055621 11203.57355028  3029.69321824
  12263.65429214  5701.18582501]
 [11624.30111738  5264.01559393 10523.38193949  5716.08003942
  13437.06971217  7069.05271949]
 [ 9186.94722079  5164.36474405  9163.25156351  6571.484544
  12618.4056054   6422.73138379]
 [10774.57402842  6062.61124329 12203.64728271  5766.3706031
  15441.79757748  7909.11388463]]


In [168]:
#log/exp(exponents)

print("\n After operation -> ")
print(np.log(m1))
print("\n After operation -> ")
print(np.exp(m1))


 After operation -> 
[[4.58912937 4.54691525 2.69593047 3.18416737]
 [1.13189284 2.82833098 4.1943108  4.20298091]
 [2.89445356 3.90586468 4.40926306 3.42418268]
 [2.66540888 4.44082622 3.30555242 4.04673088]
 [3.26794078 3.92303134 4.08593314 4.20922734]]

 After operation -> 
[[5.47472200e+42 9.37022763e+40 2.72860567e+06 3.06891268e+10]
 [2.22317540e+01 2.22355302e+07 6.26910498e+28 1.11677583e+29]
 [7.06764220e+07 3.81424504e+21 5.04491179e+35 2.14671492e+13]
 [1.74772498e+06 7.04240582e+36 6.92516890e+11 7.01521815e+24]
 [2.53141440e+11 9.01753076e+21 6.90885645e+25 1.69816529e+29]]


#### round/floor/ceil
- round means nearest value e.g 6.4 = 6 ; 6.9 = 7
- floor means previous value 6.9 or 6.5 both considerd 6
- ceil means next value 6.9 or 6.5 both considerd as 7


In [169]:
#round/floor/ceil
print(m1)
print("\n After operation -> ")
print(np.round(m1)) # Same For others

[[98.4087154  94.34094111 14.81930129 24.14717425]
 [ 3.10152163 16.91720203 66.3080162  66.8854135 ]
 [18.07362258 49.69302971 82.20885842 30.69754494]
 [14.37382549 84.8450132  27.26359846 57.21012404]
 [26.25721422 50.5534575  59.49743146 67.30451613]]

 After operation -> 
[[98. 94. 15. 24.]
 [ 3. 17. 66. 67.]
 [18. 50. 82. 31.]
 [14. 85. 27. 57.]
 [26. 51. 59. 67.]]


# Indexing and Slicing

In [170]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [171]:
# 2D Array slicing

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [219]:
print(a2,'\n')
print(a2[1,0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

4


In [173]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [174]:
a3[1,0,1]

5

In [175]:
a3[1,1,0]

6

In [176]:
a1[2:5:2]

array([2, 4])

In [177]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [222]:
#Slicing


In [179]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [180]:
a2[2,::3]

array([ 8, 11])

In [181]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [182]:
a3=np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [183]:
a3[1,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [184]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [185]:
a3[0,1]

array([3, 4, 5])

In [186]:
a3[1,:,1]

array([10, 13, 16])

In [187]:
a3[0::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [188]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [189]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

# Iterating

In [193]:
# a1 it print the full 1D array

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [198]:
print(a2,"\n\n")

for i in a2:
    print(i)

# This Loop print row-wise

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 


[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [200]:
print(a3,"\n\n")

for i in a3:
    print(i)

# Each iteration Print a 2D ARRAY

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [203]:
# fOr PRINTING EACH ITEM
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [206]:
#Transpose

print(a2,'\n\n')
print(a2.T)
print(a2,'\n Another Syntex ->')
print(np.transpose(a2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 


[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
 Another Syntex ->
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [210]:
#### ravel can convert any array into 1D Arraya1
a2
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Stacking

In [211]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [212]:
# horizontal stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [213]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [215]:
# Horizontal
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [216]:
# Vertical
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [218]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]