## np.sort
- Return a sorted copy of an array.

In [123]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([72, 11, 24, 43, 41,  1, 72, 40, 80, 40,  3, 10, 41, 86, 50])

In [124]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[87, 16, 33, 13],
       [27, 96, 86, 70],
       [37, 50, 72, 27],
       [53, 86, 18, 30],
       [53, 16, 57, 99],
       [53, 17,  1, 67]])

In [125]:
#sort 
np.sort(a)

array([ 1,  3, 10, 11, 24, 40, 40, 41, 41, 43, 50, 72, 72, 80, 86])

In [126]:
#Descending Order
np.sort(a)[::-1]

array([86, 80, 72, 72, 50, 43, 41, 41, 40, 40, 24, 11, 10,  3,  1])

In [127]:
np.sort(b,axis=0)

array([[27, 16,  1, 13],
       [37, 16, 18, 27],
       [53, 17, 33, 30],
       [53, 50, 57, 67],
       [53, 86, 72, 70],
       [87, 96, 86, 99]])

## np.append
- The numpy.append() appends values along the mentioned axis at the end of the array

In [128]:
a


array([72, 11, 24, 43, 41,  1, 72, 40, 80, 40,  3, 10, 41, 86, 50])

In [129]:
np.append(a,200)

array([ 72,  11,  24,  43,  41,   1,  72,  40,  80,  40,   3,  10,  41,
        86,  50, 200])

In [130]:
b

array([[87, 16, 33, 13],
       [27, 96, 86, 70],
       [37, 50, 72, 27],
       [53, 86, 18, 30],
       [53, 16, 57, 99],
       [53, 17,  1, 67]])

In [131]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[87.        , 16.        , 33.        , 13.        ,  0.9946206 ],
       [27.        , 96.        , 86.        , 70.        ,  0.65131752],
       [37.        , 50.        , 72.        , 27.        ,  0.22067054],
       [53.        , 86.        , 18.        , 30.        ,  0.60465905],
       [53.        , 16.        , 57.        , 99.        ,  0.71813755],
       [53.        , 17.        ,  1.        , 67.        ,  0.5405063 ]])

## np.concatenate

- numpy.concatenate() function concatenate a sequence of arrays along an existing axis.



In [132]:
c= np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [133]:
np.concatenate((c,d),axis= 0) # 0 --> row-wise

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [134]:
np.concatenate((c,d),axis= 1) # 1 --> column-wise

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

## np.unique
- With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

In [135]:
a


array([72, 11, 24, 43, 41,  1, 72, 40, 80, 40,  3, 10, 41, 86, 50])

In [136]:
# Finding the unique value
np.unique(a)

array([ 1,  3, 10, 11, 24, 40, 41, 43, 50, 72, 80, 86])

## np.expand_dims
- With the help of np.expand_dims() method, we can get the expanded dimensions of an array

In [137]:
a

array([72, 11, 24, 43, 41,  1, 72, 40, 80, 40,  3, 10, 41, 86, 50])

In [138]:
# syntax of np.expand_dims 
print(np.expand_dims(a,axis=1))

print(np.expand_dims(a,axis=1).shape)

[[72]
 [11]
 [24]
 [43]
 [41]
 [ 1]
 [72]
 [40]
 [80]
 [40]
 [ 3]
 [10]
 [41]
 [86]
 [50]]
(15, 1)


In [139]:
# column-wise
print(np.expand_dims(a,axis=0))
print(np.expand_dims(a,axis=0).shape)


[[72 11 24 43 41  1 72 40 80 40  3 10 41 86 50]]
(1, 15)


## np.where
- The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.
- jkuno condition er jonno index ber kora jay np.where(a> or any condition)
- jkuno condition onujayi change kora jay np.where(condition,True hole eta boshbe ,false)

In [140]:
a

array([72, 11, 24, 43, 41,  1, 72, 40, 80, 40,  3, 10, 41, 86, 50])

In [141]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  6,  8, 13], dtype=int64),)

In [142]:
# replace all values > 50 with 0

np.where(a>50,0,a)

array([ 0, 11, 24, 43, 41,  1,  0, 40,  0, 40,  3, 10, 41,  0, 50])

In [143]:
# replace all even numbers with 0 
np.where(a%2 == 0,0,a)

array([ 0, 11,  0, 43, 41,  1,  0,  0,  0,  0,  3,  0, 41,  0,  0])

## np.argmax
- The numpy.argmax() function returns indices of the max element of the array in a particular axis.

In [144]:
a

array([72, 11, 24, 43, 41,  1, 72, 40, 80, 40,  3, 10, 41, 86, 50])

In [145]:
np.argmax(a)

13

In [146]:
b

array([[87, 16, 33, 13],
       [27, 96, 86, 70],
       [37, 50, 72, 27],
       [53, 86, 18, 30],
       [53, 16, 57, 99],
       [53, 17,  1, 67]])

In [147]:
np.argmax(b,axis=0)

array([0, 1, 1, 4], dtype=int64)

## np.argmin

In [148]:
# argmin
np.argmin(b,axis=1)

array([3, 0, 3, 2, 1, 2], dtype=int64)

## np.cumsum
1. previous value jug hoy
2. suppose Cricketer er previous match er runlist = 50,20,65,45,85,50,0,5 .prottek match er por jodi ba agee jante chawa hoy tar total run koto tolhon jevabe amra prothom (50+20=70) then next match (70+65= total) evabe jug hoy

In [149]:
# np.cumsum 
a

array([72, 11, 24, 43, 41,  1, 72, 40, 80, 40,  3, 10, 41, 86, 50])

In [150]:
np.cumsum(a)

array([ 72,  83, 107, 150, 191, 192, 264, 304, 384, 424, 427, 437, 478,
       564, 614])

In [151]:
b

array([[87, 16, 33, 13],
       [27, 96, 86, 70],
       [37, 50, 72, 27],
       [53, 86, 18, 30],
       [53, 16, 57, 99],
       [53, 17,  1, 67]])

In [152]:
np.cumsum(b,axis=0)

array([[ 87,  16,  33,  13],
       [114, 112, 119,  83],
       [151, 162, 191, 110],
       [204, 248, 209, 140],
       [257, 264, 266, 239],
       [310, 281, 267, 306]])

In [153]:
## np.cumprod
np.cumprod(a)

array([         72,         792,       19008,      817344,    33511104,
          33511104, -1882167808,  2022699008, -1392836608,   121110528,
         363331584,  -661651456, -1357905920,  -815792128, -2134900736])

In [154]:
np.cumprod(b,axis=0)

array([[        87,         16,         33,         13],
       [      2349,       1536,       2838,        910],
       [     86913,      76800,     204336,      24570],
       [   4606389,    6604800,    3678048,     737100],
       [ 244138617,  105676800,  209648736,   72972900],
       [  54444813, 1796505600,  209648736,  594217004]])

## np.percentile
- numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.
- ki poriman luk/value current value er cheye piche (0 percentile -> lowest , 100 -> Highest , 50 -> median )
- 75%tile means ki poriman value/luk pichone 

In [155]:
a

array([72, 11, 24, 43, 41,  1, 72, 40, 80, 40,  3, 10, 41, 86, 50])

In [156]:
np.percentile(a,50)

41.0

In [157]:
np.max(a)

86

In [158]:
np.percentile(a,100)

86.0

## np.histogram
- Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.
- It basically check frequency in a given range

In [159]:
a

array([72, 11, 24, 43, 41,  1, 72, 40, 80, 40,  3, 10, 41, 86, 50])

In [160]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([2, 2, 1, 0, 5, 1, 0, 2, 2, 0], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

## np.corrcoef
- Return Pearson product-moment correlation coefficients.

In [161]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

## np.isin
- With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

- Eksathe multipe item search korte use hoy .suppose i have 5 numbers then i have to check those number against any array .

In [162]:
a

array([72, 11, 24, 43, 41,  1, 72, 40, 80, 40,  3, 10, 41, 86, 50])

In [163]:
#np.isin 
items = np.array([10,20,30,40,50,60,70,80,90,100])
#np.isin(a,items)  # check is there any matches
a[np.isin(a,items)] # Matches items array

array([40, 80, 40, 10, 50])

# np.flip 
- The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [164]:
a

array([72, 11, 24, 43, 41,  1, 72, 40, 80, 40,  3, 10, 41, 86, 50])

In [165]:
np.flip(a) # Order reverse kore dey. Jeta shurute oita sheshe hobe

array([50, 86, 41, 10,  3, 40, 80, 40, 72,  1, 41, 43, 24, 11, 72])

In [166]:
b

array([[87, 16, 33, 13],
       [27, 96, 86, 70],
       [37, 50, 72, 27],
       [53, 86, 18, 30],
       [53, 16, 57, 99],
       [53, 17,  1, 67]])

In [167]:
np.flip(b) # Row and column both order has been changed

array([[67,  1, 17, 53],
       [99, 57, 16, 53],
       [30, 18, 86, 53],
       [27, 72, 50, 37],
       [70, 86, 96, 27],
       [13, 33, 16, 87]])

In [168]:
np.flip(b,axis=0) # only row

array([[53, 17,  1, 67],
       [53, 16, 57, 99],
       [53, 86, 18, 30],
       [37, 50, 72, 27],
       [27, 96, 86, 70],
       [87, 16, 33, 13]])

## np.put
- jkuno array te any place ba index a value permanently change ba replace kore

In [169]:
a


array([72, 11, 24, 43, 41,  1, 72, 40, 80, 40,  3, 10, 41, 86, 50])

In [170]:
np.put(a,[2,5],[630,500])

In [171]:
a

array([ 72,  11, 630,  43,  41, 500,  72,  40,  80,  40,   3,  10,  41,
        86,  50])

## np.delete
- Can delete temporary
- jokhon run korle output ashbe tokhon temporary
- multiple item delete kora jay

In [172]:
a


array([ 72,  11, 630,  43,  41, 500,  72,  40,  80,  40,   3,  10,  41,
        86,  50])

In [173]:
np.delete(a,3)

array([ 72,  11, 630,  41, 500,  72,  40,  80,  40,   3,  10,  41,  86,
        50])

In [174]:
a


array([ 72,  11, 630,  43,  41, 500,  72,  40,  80,  40,   3,  10,  41,
        86,  50])

In [175]:
np.delete(a,[0,3,5])

array([ 11, 630,  41,  72,  40,  80,  40,   3,  10,  41,  86,  50])

## Set functions
- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [176]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [177]:
np.intersect1d(m,n)

array([3, 4, 5])

In [178]:
np.setdiff1d(n,m)

array([6, 7])

In [179]:
np.setxor1d(m,n) # common gula baade sobgula

array([1, 2, 6, 7])

In [180]:
m[np.in1d(m,1)] # given number ache ki na where 1 is a element

array([1])

## np.clip 
- ekta range a rakhe value-gula
- suppose ami chai amr value gula jeno 25 theke 75 er modde hoy .j gula 25 theke chuto oigula 25 dara replace hobe and Boro value 75 dara

In [181]:
a

array([ 72,  11, 630,  43,  41, 500,  72,  40,  80,  40,   3,  10,  41,
        86,  50])

In [182]:
np.clip(a,a_min=25,a_max=75)

array([72, 25, 75, 43, 41, 75, 72, 40, 75, 40, 25, 25, 41, 75, 50])

In [183]:
## 19. np.count_nonzero 
## 17. np.swapaxesa
# 18. np.uniform