###  What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types arrays.

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

## Creating a Numpy Array

In [1]:
import numpy as np
numArr = np.array([14,15,85,856])
print(numArr)

[ 14  15  85 856]


###### Creating 2D Array

In [2]:
# Array MUst be HOMOGENOUS
numArr_02 = np.array([[56,69,54,35],[856,45,86,858]])
print(numArr_02)

[[ 56  69  54  35]
 [856  45  86 858]]


##### 3D Array

In [3]:
ar_o3 = np.array([[[5,6,85],[8,9,56],[8,56,58],[5,6,85]]])
print(ar_o3.ndim)  #Checking Dimension
print(ar_o3)

3
[[[ 5  6 85]
  [ 8  9 56]
  [ 8 56 58]
  [ 5  6 85]]]


In [4]:
#Creating Specific DataType Array

np.array([1,9,8,45,5],dtype = float)



array([ 1.,  9.,  8., 45.,  5.])

##### Arange use
- work as similar as range
- can be used almost similar way like the range 

In [5]:
# arange it works similer like range 

ar_04=np.arange(1,12)
print(ar_04)

#Another Like the gap values 
array_5 = np.arange(1,11,2)
print(array_5)

[ 1  2  3  4  5  6  7  8  9 10 11]
[1 3 5 7 9]


In [6]:
# Reshape 
# total items should be equal to the product of 2 items in reshape
#Example: Given 1 to 10 .we must choose using the product of the total elements either (2,5) or (5,2)
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

##### Using np.ones & np.zeros


In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
#np.zeros
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# np.random it will generate random numbers in between 0 to 1
np.random.random((4,4))

array([[0.71122054, 0.88109249, 0.92439959, 0.17684028],
       [0.17383798, 0.66446585, 0.29300626, 0.90154915],
       [0.71954327, 0.84096889, 0.60013074, 0.77486904],
       [0.46495515, 0.66694557, 0.97105674, 0.93364427]])

##### linspace
- it takes 3 parameter
- e.g np.linspace((-10,15,10))
- first parameter(-10) = lower limits,  
  second parameter(15) = upper limits,  
  Third parameter(10) = How many numbers you want

- It will generate number between similar distance.Any two numbers distance/difference will be equal


In [10]:
np.linspace(-10,15,10)

#custom_size = np.linspace(-10,15,10).reshape(5,2)
#print(custom_size)

array([-10.        ,  -7.22222222,  -4.44444444,  -1.66666667,
         1.11111111,   3.88888889,   6.66666667,   9.44444444,
        12.22222222,  15.        ])

##### creating Identity Matrix

In [11]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Array Attributes


## Important Notes About reshape(2,2,2)
#### The reshape function is used to change the shape of an array without changing its data. The reshape(2, 2, 2) command reshapes an array into a 3-dimensional array with dimensions 2x2x2 
- The first argument 2 specifies that the reshaped array will have 2 blocks.
- The second argument 2 specifies that each block will have 2 rows.
- The third argument 2 specifies that each row will have 2 columns.
### Caution

- The total number of elements in the original array must match the total number of elements in the reshaped array. For example, in this case, 2 * 2 * 2 = 8, which matches the 8 elements in the original array.
- If the dimensions do not match, NumPy will raise an error.

In [12]:
#ndim
a1 = np.arange(10)
a2 = np.arange(9).reshape(3,3)
a3 = np.arange(8,dtype=float).reshape(2,2,2)
a2.ndim


2

In [13]:
a3.itemsize

8

In [14]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
int32
float64


##### shape
- How many rows and columns
- also dimension

In [15]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

##### itemsize
- how many bits are taking

In [16]:
a1.itemsize

4

#### size
- total size of the array

In [17]:
print(a3)
print(np.size(a3))

[[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]
8


#### astype 
- jodi kokhono datatype change korte hoy
- e.g int64 to int32
- reduce size

In [18]:
# astype 

a3.astype(np.int64)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

# Array Operation

#### Scaler Operation
- matrix er moto 
-  5 x matrix means prottek element er sathe 5 gun

In [19]:
print(a2)
print("\n\n After Multiplication -> ")
print(a2*2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


 After Multiplication -> 
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


#### Relational Operation 
- Performing relational operation  like < , > , == ,<= etc

In [20]:
# Relational
print(a2)
print("\n\n After  -> ")
print(a2==8)
print("\n\n After : -> ")
print(a2 > 4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


 After  -> 
[[False False False]
 [False False False]
 [False False  True]]


 After : -> 
[[False False False]
 [False False  True]
 [ True  True  True]]


In [21]:
# Vector Operationa1
# a2 + a2
a2 * a2


array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

# Array Functions 

#### max/min/sum/prod
- calculate max/min/prod
- axix=0 ->  column; axis = 1 -> row
- syntax: np.prod(a2) or  np.max(a2,axis=0 )

In [22]:
print(a2)
print("\nAfter operation -> ")
print(np.max(a2)) # higest in whole matrix

print("\n After operation -> ")
print(np.max(a2, axis=1))


[[0 1 2]
 [3 4 5]
 [6 7 8]]

After operation -> 
8

 After operation -> 
[2 5 8]


In [23]:
# mean/median/std/var
np.mean(a3) # can perform all

3.5

In [24]:
# Trigonomatrica
np.sin(a3)

array([[[ 0.        ,  0.84147098],
        [ 0.90929743,  0.14112001]],

       [[-0.7568025 , -0.95892427],
        [-0.2794155 ,  0.6569866 ]]])

#### Dot Product
- 1st matrix er column songkha == second matrix er Row songkha
- e.g (5,4) * (4*6)

In [25]:
m1 = np.random.random((5,4))*100
m2 = np.random.random((4,6))*100
print(m1)
print("\n After operation -> \n")
print(np.dot(m1,m2))

[[53.73925377 22.13439884 19.05309789  5.59094498]
 [52.31567793 99.46670096 22.08080827 77.56833127]
 [84.67214765 20.44542339 85.29559377 47.24074512]
 [55.72561165 79.69062996 67.17548489 61.71259942]
 [ 2.26669946 16.89345958  5.45775286 94.89646017]]

 After operation -> 

[[ 7993.55356703  2245.05144297  3820.84819215  4868.31348475
   1440.35456018  5760.13783537]
 [16586.76959472 11815.0892912  10392.0589639  14880.06405205
   5385.53476896  7265.14152814]
 [15208.07979615  8323.43456182  9145.52720131 13083.09907074
   4480.65046242 13781.63479438]
 [17634.80592058 10903.59530513 11140.74868103 16980.53584022
   5236.1154244  10560.24447441]
 [ 3376.0611055   9935.33719674  4187.53161844  5389.61393339
   4128.44614348  2213.11905216]]


In [26]:
#log/exp(exponents)

print("\n After operation -> ")
print(np.log(m1))
print("\n After operation -> ")
print(np.exp(m1))


 After operation -> 
[[3.98414372 3.09713291 2.94722971 1.72114832]
 [3.9572961  4.59982292 3.09470883 4.35115924]
 [4.43878671 3.01775906 4.4461228  3.85525676]
 [4.02043986 4.37815201 4.20730837 4.12248811]
 [0.81832479 2.82692654 1.69703714 4.5527864 ]]

 After operation -> 
[[2.18102866e+23 4.10059877e+09 1.88215453e+08 2.67988744e+02]
 [5.25303435e+22 1.57702784e+43 3.88662990e+09 4.86965554e+33]
 [5.92442892e+36 7.57416146e+08 1.10511050e+37 3.28393782e+20]
 [1.58973831e+24 4.06631343e+34 1.49259646e+29 6.33054928e+26]
 [9.64750621e+00 2.17138222e+07 2.34569721e+02 1.63308580e+41]]


#### round/floor/ceil
- round means nearest value e.g 6.4 = 6 ; 6.9 = 7
- floor means previous value 6.9 or 6.5 both considerd 6
- ceil means next value 6.9 or 6.5 both considerd as 7


In [27]:
#round/floor/ceil
print(m1)
print("\n After operation -> ")
print(np.round(m1)) # Same For others

[[53.73925377 22.13439884 19.05309789  5.59094498]
 [52.31567793 99.46670096 22.08080827 77.56833127]
 [84.67214765 20.44542339 85.29559377 47.24074512]
 [55.72561165 79.69062996 67.17548489 61.71259942]
 [ 2.26669946 16.89345958  5.45775286 94.89646017]]

 After operation -> 
[[54. 22. 19.  6.]
 [52. 99. 22. 78.]
 [85. 20. 85. 47.]
 [56. 80. 67. 62.]
 [ 2. 17.  5. 95.]]


# Indexing and Slicing

In [28]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [29]:
# 2D Array slicing

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
print(a2,'\n')
print(a2[1,0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

4


In [31]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [32]:
a3[1,0,1]

5

In [33]:
a3[1,1,0]

6

In [34]:
a1[2:5:2]

array([2, 4])

In [35]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
#Slicing


In [37]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [38]:
a2[2,::3]

array([ 8, 11])

In [39]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [40]:
a3=np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [41]:
a3[1,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [42]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [43]:
a3[0,1]

array([3, 4, 5])

In [44]:
a3[1,:,1]

array([10, 13, 16])

In [45]:
a3[0::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [46]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [47]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

# Iterating

In [48]:
# a1 it print the full 1D array

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [49]:
print(a2,"\n\n")

for i in a2:
    print(i)

# This Loop print row-wise

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 


[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [50]:
print(a3,"\n\n")

for i in a3:
    print(i)

# Each iteration Print a 2D ARRAY

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [51]:
# fOr PRINTING EACH ITEM
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [52]:
#Transpose

print(a2,'\n\n')
print(a2.T)
print(a2,'\n Another Syntex ->')
print(np.transpose(a2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 


[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
 Another Syntex ->
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [53]:
#### ravel can convert any array into 1D Arraya1
a2
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Stacking

In [54]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [55]:
# horizontal stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [56]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [57]:
# Horizontal
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [58]:
# Vertical
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [59]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]